# Form implementation generated from reading ui file 'janela2.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.resize(320, 343)
        self.centralwidget = QtWidgets.QWidget(parent=Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_nome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_nome.setStyleSheet("")
        self.label_nome.setObjectName("label_nome")
        self.verticalLayout.addWidget(self.label_nome)
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.verticalLayout.addWidget(self.lineEdit_nome)
        self.label__sobrenome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label__sobrenome.setObjectName("label__sobrenome")
        self.verticalLayout.addWidget(self.label__sobrenome)
        self.lineEdit__sobrenome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit__sobrenome.setObjectName("lineEdit__sobrenome")
        self.verticalLayout.addWidget(self.lineEdit__sobrenome)
        self.pushButton_unir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_unir.setObjectName("pushButton_unir")
        self.verticalLayout.addWidget(self.pushButton_unir)
        self.label__completo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label__completo.setObjectName("label__completo")
        self.verticalLayout.addWidget(self.label__completo)
        self.lineEdit_completo = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_completo.setStyleSheet("backgroud:rgb(0, 255, 0)")
        self.lineEdit_completo.setText("")
        self.lineEdit_completo.setReadOnly(True)
        self.lineEdit_completo.setObjectName("lineEdit_completo")
        self.verticalLayout.addWidget(self.lineEdit_completo)
        Janela.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Janela)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 320, 21))
        self.menubar.setObjectName("menubar")
        Janela.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Janela)
        self.statusbar.setObjectName("statusbar")
        Janela.setStatusBar(self.statusbar)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "Nomelator"))
        self.label_nome.setText(_translate("Janela", "Nome:"))
        self.lineEdit_nome.setText(_translate("Janela", ""))
        self.label__sobrenome.setText(_translate("Janela", "Sobrenome:"))
        self.lineEdit__sobrenome.setText(_translate("Janela", ""))
        self.pushButton_unir.setText(_translate("Janela", "Unir"))
        self.pushButton_unir.clicked.connect(self.unir)
        self.label__completo.setText(_translate("Janela", "Nome Completo:"))

    def unir(self):
        nome = self.lineEdit_nome.text()
        sobre = self.lineEdit__sobrenome.text()
        self.lineEdit_completo.setText(nome+ " " + sobre)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Janela = QtWidgets.QMainWindow()
    ui = Ui_Janela()
    ui.setupUi(Janela)
    Janela.show()
    sys.exit(app.exec())
