# Form implementation generated from reading ui file 'janela3.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.resize(422, 226)
        self.centralwidget = QtWidgets.QWidget(parent=Janela)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_valor1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_valor1.setObjectName("label_valor1")
        self.verticalLayout.addWidget(self.label_valor1)
        self.lineEdit_valor1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_valor1.setObjectName("lineEdit_valor1")
        self.verticalLayout.addWidget(self.lineEdit_valor1)
        self.label__valor2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label__valor2.setObjectName("label__valor2")
        self.verticalLayout.addWidget(self.label__valor2)
        self.lineEdit__valor2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit__valor2.setObjectName("lineEdit__valor2")
        self.verticalLayout.addWidget(self.lineEdit__valor2)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.pushButton_Enviar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_Enviar.setObjectName("pushButton_Enviar")
        self.verticalLayout.addWidget(self.pushButton_Enviar)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit_total = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_total.setObjectName("lineEdit_total")
        self.verticalLayout.addWidget(self.lineEdit_total)
        Janela.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Janela)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 422, 21))
        self.menubar.setObjectName("menubar")
        Janela.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Janela)
        self.statusbar.setObjectName("statusbar")
        Janela.setStatusBar(self.statusbar)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "Somador"))
        self.label_valor1.setText(_translate("Janela", "valor 1:"))
        self.label__valor2.setText(_translate("Janela", "valor 2:"))
        self.pushButton_Enviar.setText(_translate("Janela", "Enviar"))
        self.pushButton_Enviar.clicked.connect(self.soma)
        self.label.setText(_translate("Janela", "Total"))

    def soma(self):
        nome = int(self.lineEdit_valor1.text())
        sobre = int(self.lineEdit__valor2.text())
        self.lineEdit_total.setText(str(nome + sobre))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Janela = QtWidgets.QMainWindow()
    ui = Ui_Janela()
    ui.setupUi(Janela)
    Janela.show()
    sys.exit(app.exec())
