# Form implementation generated from reading ui file 'janela_atualizar.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
conexao = mysql.connector.connect(
    host='localhost', user='root',
    password='', database='escola'
)
cursor = conexao.cursor()
print('conectado ao DB')

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(560, 615)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 371, 25))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_codigo = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_codigo.setObjectName("label_codigo")
        self.horizontalLayout.addWidget(self.label_codigo)
        self.lineEdit_codigo = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.lineEdit_codigo.setObjectName("lineEdit_codigo")
        self.horizontalLayout.addWidget(self.lineEdit_codigo)
        self.pushButton = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(self.abrir)

        self.horizontalLayout.addWidget(self.pushButton)
        self.label_nome = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_nome.setGeometry(QtCore.QRect(20, 40, 31, 16))
        self.label_nome.setObjectName("label_nome")
        self.lineEdit_nome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_nome.setGeometry(QtCore.QRect(70, 40, 321, 20))
        self.lineEdit_nome.setObjectName("lineEdit_nome")
        self.label_curso = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_curso.setGeometry(QtCore.QRect(20, 110, 32, 16))
        self.label_curso.setObjectName("label_curso")
        self.comboBox_curso = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_curso.setGeometry(QtCore.QRect(60, 110, 331, 20))
        self.comboBox_curso.setObjectName("comboBox_curso")
        self.comboBox_curso.addItem("")
        self.comboBox_curso.addItem("")
        self.comboBox_curso.addItem("")
        self.comboBox_curso.addItem("")
        self.label_turno = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_turno.setGeometry(QtCore.QRect(20, 80, 30, 16))
        self.label_turno.setObjectName("label_turno")
        self.label_extra = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_extra.setGeometry(QtCore.QRect(20, 150, 41, 20))
        self.label_extra.setObjectName("label_extra")
        self.label_obs = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_obs.setGeometry(QtCore.QRect(20, 200, 61, 16))
        self.label_obs.setObjectName("label_obs")
        self.pushButton_salva = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_salva.setGeometry(QtCore.QRect(40, 430, 361, 23))
        self.pushButton_salva.setObjectName("pushButton_salva")
        self.textEdit_obs = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_obs.setGeometry(QtCore.QRect(130, 190, 256, 192))
        self.textEdit_obs.setObjectName("textEdit_obs")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(70, 80, 331, 21))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_manha_2 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget_2)
        self.radioButton_manha_2.setChecked(True)
        self.radioButton_manha_2.setObjectName("radioButton_manha_2")
        self.horizontalLayout_4.addWidget(self.radioButton_manha_2)
        self.radioButton_tarde_2 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget_2)
        self.radioButton_tarde_2.setObjectName("radioButton_tarde_2")
        self.horizontalLayout_4.addWidget(self.radioButton_tarde_2)
        self.radioButton_noite_2 = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget_2)
        self.radioButton_noite_2.setObjectName("radioButton_noite_2")
        self.horizontalLayout_4.addWidget(self.radioButton_noite_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 150, 321, 20))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_atleta_2 = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget_3)
        self.checkBox_atleta_2.setObjectName("checkBox_atleta_2")
        self.horizontalLayout_5.addWidget(self.checkBox_atleta_2)
        self.checkBox_bolsista_2 = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget_3)
        self.checkBox_bolsista_2.setObjectName("checkBox_bolsista_2")
        self.horizontalLayout_5.addWidget(self.checkBox_bolsista_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_codigo.setText(_translate("MainWindow", "Código"))
        self.pushButton.setText(_translate("MainWindow", "Abrir"))
        self.label_nome.setText(_translate("MainWindow", "Nome:"))
        self.label_curso.setText(_translate("MainWindow", "Curso:"))
        self.comboBox_curso.setItemText(0, _translate("MainWindow", "Informatica"))
        self.comboBox_curso.setItemText(1, _translate("MainWindow", "edificaçoes"))
        self.comboBox_curso.setItemText(2, _translate("MainWindow", "eletrica"))
        self.comboBox_curso.setItemText(3, _translate("MainWindow", "mecanica"))
        self.label_turno.setText(_translate("MainWindow", "turno:"))
        self.label_extra.setText(_translate("MainWindow", "Extra:"))
        self.label_obs.setText(_translate("MainWindow", "Obs.:"))
        self.pushButton_salva.setText(_translate("MainWindow", "Atualizar"))
        self.radioButton_manha_2.setText(_translate("MainWindow", "Manhã"))
        self.radioButton_tarde_2.setText(_translate("MainWindow", "Tarde"))
        self.radioButton_noite_2.setText(_translate("MainWindow", "Noite"))
        self.checkBox_atleta_2.setText(_translate("MainWindow", "Atleta"))
        self.checkBox_bolsista_2.setText(_translate("MainWindow", "Bolsista"))

    def abrir(self):
        codigo = self.lineEdit_codigo.text()
        sql= "SELECT * FROM aluno WHERE codigo = " + codigo
        cursor.execute(sql)
        dados = cursor.fetchone()

        if len(dados) >0: # o registro existe
            self.lineEdit_nome.setText(dados[1])

        else:
            print('REGISTRO NÃO ENCONTRADO')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
