# Form implementation generated from reading ui file 'cadastro.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem, QMessageBox


import mysql.connector
conexao = mysql.connector.connect(
    host='localhost', user='root',
    password='', database='lojaroupa'
)
cursor = conexao.cursor()


class Ui_telaCadastro(object):
    def setupUi(self, telaCadastro):
        telaCadastro.setObjectName("telaCadastro")
        telaCadastro.resize(809, 541)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(telaCadastro.sizePolicy().hasHeightForWidth())
        telaCadastro.setSizePolicy(sizePolicy)
        telaCadastro.setMaximumSize(QtCore.QSize(16777215, 8000))
        telaCadastro.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        telaCadastro.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icones/roupas-masculinas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        telaCadastro.setWindowIcon(icon)
        telaCadastro.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=telaCadastro)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_titulo.setGeometry(QtCore.QRect(80, 0, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_titulo.setFont(font)
        self.label_titulo.setObjectName("label_titulo")
        self.label_background = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_background.setGeometry(QtCore.QRect(410, 0, 401, 541))
        self.label_background.setStyleSheet("background-image: url(:/ico/retrato.jpg);\n"
"\n"
"")
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap("imagens/retrato.jpg"))
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")
        self.label_turno = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_turno.setGeometry(QtCore.QRect(10, 180, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_turno.setFont(font)
        self.label_turno.setObjectName("label_turno")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 180, 251, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_manha = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.radioButton_manha.setChecked(True)
        self.radioButton_manha.setObjectName("radioButton_manha")
        self.horizontalLayout_2.addWidget(self.radioButton_manha)
        self.radioButton_tarde = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.radioButton_tarde.setObjectName("radioButton_tarde")
        self.horizontalLayout_2.addWidget(self.radioButton_tarde)
        self.radioButton_noite = QtWidgets.QRadioButton(parent=self.layoutWidget)
        self.radioButton_noite.setObjectName("radioButton_noite")
        self.horizontalLayout_2.addWidget(self.radioButton_noite)
        self.textEdit_obs = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit_obs.setGeometry(QtCore.QRect(10, 300, 391, 161))
        self.textEdit_obs.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"border-top:2px solid rgba(46,82,101,200);\n"
"border-left:2px solid rgba(46,82,101,200);\n"
"border-right:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.textEdit_obs.setObjectName("textEdit_obs")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 90, 391, 29))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_funcionario = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_funcionario.setFont(font)
        self.label_funcionario.setObjectName("label_funcionario")
        self.horizontalLayout_6.addWidget(self.label_funcionario)
        self.comboBox_tipo_Funcinario = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_4)
        self.comboBox_tipo_Funcinario.setStyleSheet("")
        self.comboBox_tipo_Funcinario.setObjectName("comboBox_tipo_Funcinario")
        self.comboBox_tipo_Funcinario.addItem("")
        self.comboBox_tipo_Funcinario.addItem("")
        self.comboBox_tipo_Funcinario.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_tipo_Funcinario)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(10, 130, 391, 31))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_senha = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_senha.setFont(font)
        self.label_senha.setObjectName("label_senha")
        self.horizontalLayout_8.addWidget(self.label_senha)
        self.checkBox_remunerado = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget_6)
        self.checkBox_remunerado.setObjectName("checkBox_remunerado")
        self.horizontalLayout_8.addWidget(self.checkBox_remunerado)
        self.checkBox_estagiario = QtWidgets.QCheckBox(parent=self.horizontalLayoutWidget_6)
        self.checkBox_estagiario.setObjectName("checkBox_estagiario")
        self.horizontalLayout_8.addWidget(self.checkBox_estagiario)
        self.label_obs = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_obs.setGeometry(QtCore.QRect(10, 270, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_obs.setFont(font)
        self.label_obs.setObjectName("label_obs")
        self.line_nome = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_nome.setGeometry(QtCore.QRect(8, 50, 391, 25))
        self.line_nome.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.line_nome.setObjectName("line_nome")
        self.line_senha = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_senha.setGeometry(QtCore.QRect(10, 230, 391, 25))
        self.line_senha.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.line_senha.setText("")
        self.line_senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_senha.setObjectName("line_senha")
        self.botao_salvar_funcionario = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botao_salvar_funcionario.setGeometry(QtCore.QRect(10, 480, 391, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.botao_salvar_funcionario.setFont(font)
        self.botao_salvar_funcionario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.botao_salvar_funcionario.setStyleSheet("QPushButton#PushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        self.botao_salvar_funcionario.setObjectName("botao_salvar_funcionario")

        self.botao_salvar_funcionario.clicked.connect(self.cadastrarUsuario)

        self.label_barra = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_barra.setGeometry(QtCore.QRect(10, 200, 391, 20))
        self.label_barra.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.label_barra.setText("")
        self.label_barra.setObjectName("label_barra")
        self.label_barra_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_barra_2.setGeometry(QtCore.QRect(10, 110, 391, 20))
        self.label_barra_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.label_barra_2.setText("")
        self.label_barra_2.setObjectName("label_barra_2")
        self.label_barra2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_barra2.setGeometry(QtCore.QRect(10, 150, 391, 20))
        self.label_barra2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.label_barra2.setText("")
        self.label_barra2.setObjectName("label_barra2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 411, 541))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(250, 215, 247, 0.418), stop:1 rgba(75, 136, 228, 0.5));\n"
"\n"
"border-color: rgb(85, 255, 0);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label.raise_()
        self.label_titulo.raise_()
        self.label_background.raise_()
        self.label_turno.raise_()
        self.layoutWidget.raise_()
        self.textEdit_obs.raise_()
        self.horizontalLayoutWidget_4.raise_()
        self.horizontalLayoutWidget_6.raise_()
        self.label_obs.raise_()
        self.line_nome.raise_()
        self.line_senha.raise_()
        self.botao_salvar_funcionario.raise_()
        self.label_barra.raise_()
        self.label_barra_2.raise_()
        self.label_barra2.raise_()
        telaCadastro.setCentralWidget(self.centralwidget)

        self.retranslateUi(telaCadastro)
        QtCore.QMetaObject.connectSlotsByName(telaCadastro)

    def retranslateUi(self, telaCadastro):
        _translate = QtCore.QCoreApplication.translate
        telaCadastro.setWindowTitle(_translate("telaCadastro", "Cadastre-se"))
        self.label_titulo.setText(_translate("telaCadastro", "Cadastro de Funcionarios"))
        self.label_turno.setText(_translate("telaCadastro", "Turno"))
        self.radioButton_manha.setText(_translate("telaCadastro", "Manhã"))
        self.radioButton_tarde.setText(_translate("telaCadastro", "Tarde"))
        self.radioButton_noite.setText(_translate("telaCadastro", "Noite"))
        self.label_funcionario.setText(_translate("telaCadastro", "Tipo de Funcionário"))
        self.comboBox_tipo_Funcinario.setItemText(0, _translate("telaCadastro", "Logístico"))
        self.comboBox_tipo_Funcinario.setItemText(1, _translate("telaCadastro", "Vendedor"))
        self.comboBox_tipo_Funcinario.setItemText(2, _translate("telaCadastro", "Entregador"))
        self.label_senha.setText(_translate("telaCadastro", "Extra:"))
        self.checkBox_remunerado.setText(_translate("telaCadastro", "Remunerado"))
        self.checkBox_estagiario.setText(_translate("telaCadastro", "Estagiario"))
        self.label_obs.setText(_translate("telaCadastro", "Observações:"))
        self.line_nome.setPlaceholderText(_translate("telaCadastro", "nome de usuario"))
        self.line_senha.setPlaceholderText(_translate("telaCadastro", "Senha"))
        self.botao_salvar_funcionario.setText(_translate("telaCadastro", "SALVA"))


    def cadastrarUsuario(self):
        nome = self.line_nome.text()
        senha = self.line_senha.text()
        tipoFuncionario = self.comboBox_tipo_Funcinario.currentText()

        turno = ""
        if self.radioButton_manha.isChecked():
            turno = "Manhã"
        elif self.radioButton_tarde.isChecked():
            turno = "Tarde"
        elif self.radioButton_noite.isChecked():
            turno = "Noite"

        estagiario = 'Não'
        if self.checkBox_estagiario.isChecked():
            estagiario = 'Sim'

        resunerado = 'não'
        if self.checkBox_remunerado.isChecked():
            resunerado = 'sim'

        obs = self.textEdit_obs.toPlainText()
        print(nome,senha, tipoFuncionario, turno, estagiario, resunerado, obs)

        sql = "INSERT INTO usuarios VALUES(null,%s,%s,%s,%s,%s,%s,%s)"
        cursor.execute(sql, (nome,senha, tipoFuncionario, turno, estagiario, resunerado, obs))
        conexao.commit()
        # print('INSERIDO COM SUCESSO')


        msg = QMessageBox()
        msg.setWindowTitle('AVISO')
        msg.setText('inserido com sucesso')
        msg.exec()

        # limpar os campos
        self.line_nome.setText('')
        self.line_senha.setText('')
        self.comboBox_tipo_Funcinario.setCurrentIndex(0)
        self.radioButton_manha.setChecked(True)
        self.radioButton_noite.setChecked(False)  # opcional
        self.radioButton_tarde.setChecked(False)  # opcional
        self.checkBox_estagiario.setChecked(False)
        self.checkBox_remunerado.setChecked(False)
        self.textEdit_obs.setPlainText("")

        self.line_nome.setFocus()  # faz com o que o campo já esteja pronto para digitar

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telaCadastro = QtWidgets.QMainWindow()
    ui = Ui_telaCadastro()
    ui.setupUi(telaCadastro)
    telaCadastro.show()
    sys.exit(app.exec())
