# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.




from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QTableWidgetItem, QMessageBox


import mysql.connector
conexao = mysql.connector.connect(
    host='localhost', user='root',
    password='', database='lojaroupa'
)
cursor = conexao.cursor()


class Ui_LojadeRoupa(object):
    def setupUi(self, LojadeRoupa):
        LojadeRoupa.setObjectName("LojadeRoupa")
        LojadeRoupa.resize(831, 576)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icones/roupas-masculinas.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        LojadeRoupa.setWindowIcon(icon)
        self.Menu = QtWidgets.QWidget(parent=LojadeRoupa)
        self.Menu.setObjectName("Menu")
        self.verticalWidget_miniMenu = QtWidgets.QWidget(parent=self.Menu)
        self.verticalWidget_miniMenu.setGeometry(QtCore.QRect(60, 270, 171, 251))
        self.verticalWidget_miniMenu.setAutoFillBackground(False)
        self.verticalWidget_miniMenu.setObjectName("verticalWidget_miniMenu")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget_miniMenu)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_login = QtWidgets.QPushButton(parent=self.verticalWidget_miniMenu)
        self.pushButton_login.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_login.setStyleSheet("border-radius: 10px;font-size:18px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icones/log-in.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_login.setIcon(icon1)
        self.pushButton_login.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_login.setObjectName("pushButton_login")
        self.verticalLayout.addWidget(self.pushButton_login, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.pushButton_cadastrar = QtWidgets.QPushButton(parent=self.verticalWidget_miniMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cadastrar.sizePolicy().hasHeightForWidth())
        self.pushButton_cadastrar.setSizePolicy(sizePolicy)
        self.pushButton_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_cadastrar.setStyleSheet("border-radius: 10px;font-size:18px;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icones/book-open.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_cadastrar.setIcon(icon2)
        self.pushButton_cadastrar.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_cadastrar.setObjectName("pushButton_cadastrar")
        self.verticalLayout.addWidget(self.pushButton_cadastrar, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.pushButton_cadastrar_usuario = QtWidgets.QPushButton(parent=self.verticalWidget_miniMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cadastrar_usuario.sizePolicy().hasHeightForWidth())
        self.pushButton_cadastrar_usuario.setSizePolicy(sizePolicy)
        self.pushButton_cadastrar_usuario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_cadastrar_usuario.setStyleSheet("border-radius: 10px;font-size:18px;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icones/add-user.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_cadastrar_usuario.setIcon(icon3)
        self.pushButton_cadastrar_usuario.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_cadastrar_usuario.setObjectName("pushButton_cadastrar_usuario")
        self.verticalLayout.addWidget(self.pushButton_cadastrar_usuario, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButton_cadastrar_vestuario = QtWidgets.QPushButton(parent=self.verticalWidget_miniMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cadastrar_vestuario.sizePolicy().hasHeightForWidth())
        self.pushButton_cadastrar_vestuario.setSizePolicy(sizePolicy)
        self.pushButton_cadastrar_vestuario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_cadastrar_vestuario.setStyleSheet("border-radius: 10px;font-size:18px;")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icones/hanger.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_cadastrar_vestuario.setIcon(icon4)
        self.pushButton_cadastrar_vestuario.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_cadastrar_vestuario.setObjectName("pushButton_cadastrar_vestuario")
        self.verticalLayout.addWidget(self.pushButton_cadastrar_vestuario, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.pushButton_pesquisa = QtWidgets.QPushButton(parent=self.verticalWidget_miniMenu)
        self.pushButton_pesquisa.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_pesquisa.setStyleSheet("border-radius: 10px;font-size:18px;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icones/search.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_pesquisa.setIcon(icon5)
        self.pushButton_pesquisa.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_pesquisa.setObjectName("pushButton_pesquisa")
        self.verticalLayout.addWidget(self.pushButton_pesquisa, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.pushButton_sobre = QtWidgets.QPushButton(parent=self.verticalWidget_miniMenu)
        self.pushButton_sobre.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_sobre.setAutoFillBackground(False)
        self.pushButton_sobre.setStyleSheet("border-radius: 10px;font-size:18px;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icones/users.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_sobre.setIcon(icon6)
        self.pushButton_sobre.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_sobre.setObjectName("pushButton_sobre")
        self.verticalLayout.addWidget(self.pushButton_sobre, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_left_Image = QtWidgets.QLabel(parent=self.Menu)
        self.label_left_Image.setGeometry(QtCore.QRect(0, 0, 281, 601))
        self.label_left_Image.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.label_left_Image.setStyleSheet("opacity:0.5;")
        self.label_left_Image.setText("")
        self.label_left_Image.setPixmap(QtGui.QPixmap("imagens/label_left_Image.png"))
        self.label_left_Image.setScaledContents(True)
        self.label_left_Image.setObjectName("label_left_Image")
        self.label_nome_sistema_de_loja = QtWidgets.QLabel(parent=self.Menu)
        self.label_nome_sistema_de_loja.setGeometry(QtCore.QRect(50, 0, 201, 51))
        self.label_nome_sistema_de_loja.setStyleSheet("font: italic 25pt \"Brush Script MT\";")
        self.label_nome_sistema_de_loja.setObjectName("label_nome_sistema_de_loja")
        self.StackedWidget_Paginas = QtWidgets.QStackedWidget(parent=self.Menu)
        self.StackedWidget_Paginas.setEnabled(True)
        self.StackedWidget_Paginas.setGeometry(QtCore.QRect(260, 0, 571, 611))
        self.StackedWidget_Paginas.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.SizeHorCursor))
        self.StackedWidget_Paginas.setAutoFillBackground(False)
        self.StackedWidget_Paginas.setStyleSheet("backgroud:rgb(255,255,255)")
        self.StackedWidget_Paginas.setObjectName("StackedWidget_Paginas")
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.widget_login = QtWidgets.QWidget(parent=self.page_login)
        self.widget_login.setGeometry(QtCore.QRect(20, 30, 550, 500))
        self.widget_login.setStyleSheet("QPushButton#pushButton{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}\n"
"    \n"
"QPushButton#pushButton_2, #pushButton_3, #pushButton_4, #pushButton_5{\n"
"    background-color: rgba(0, 0, 0, 0);\n"
"    color:rgba(85, 98, 112, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{\n"
"    color: rgba(131, 96, 53, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_2:pressed, #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    color:rgba(91, 88, 53, 255);\n"
"}\n"
"")
        self.widget_login.setObjectName("widget_login")
        self.label_imagem_login = QtWidgets.QLabel(parent=self.widget_login)
        self.label_imagem_login.setGeometry(QtCore.QRect(10, -10, 280, 441))
        self.label_imagem_login.setStyleSheet("border-image: url(:/images/background.jpg);\n"
"\n"
"\n"
"border-top-left-radius:50px;")
        self.label_imagem_login.setText("")
        self.label_imagem_login.setPixmap(QtGui.QPixmap("imagens/login_imagem.jpeg"))
        self.label_imagem_login.setScaledContents(True)
        self.label_imagem_login.setObjectName("label_imagem_login")
        self.label_fundo_card_login = QtWidgets.QLabel(parent=self.widget_login)
        self.label_fundo_card_login.setGeometry(QtCore.QRect(280, 0, 240, 430))
        self.label_fundo_card_login.setStyleSheet("border-bottom-right-radius: 50px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(250, 215, 247, 0.418), stop:1 rgba(75, 136, 228, 0.5));\n"
"\n"
"border-color: rgb(85, 255, 0);")
        self.label_fundo_card_login.setText("")
        self.label_fundo_card_login.setObjectName("label_fundo_card_login")
        self.label_login = QtWidgets.QLabel(parent=self.widget_login)
        self.label_login.setGeometry(QtCore.QRect(370, 50, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_login.setFont(font)
        self.label_login.setStyleSheet("color:rgba(0,0,0,200);")
        self.label_login.setObjectName("label_login")
        self.line_usuario = QtWidgets.QLineEdit(parent=self.widget_login)
        self.line_usuario.setGeometry(QtCore.QRect(310, 100, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_usuario.setFont(font)
        self.line_usuario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.line_usuario.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.line_usuario.setObjectName("line_usuario")
        self.line_senha = QtWidgets.QLineEdit(parent=self.widget_login)
        self.line_senha.setGeometry(QtCore.QRect(310, 160, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_senha.setFont(font)
        self.line_senha.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.line_senha.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.line_senha.setText("")
        self.line_senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_senha.setObjectName("line_senha")
        self.botao_entrar = QtWidgets.QPushButton(parent=self.widget_login)
        self.botao_entrar.setGeometry(QtCore.QRect(310, 240, 190, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.botao_entrar.setFont(font)
        self.botao_entrar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.botao_entrar.setStyleSheet("QPushButton#PushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        self.botao_entrar.setObjectName("botao_entrar")
        self.label_4_esqueceuSenha = QtWidgets.QLabel(parent=self.widget_login)
        self.label_4_esqueceuSenha.setGeometry(QtCore.QRect(320, 310, 181, 16))
        self.label_4_esqueceuSenha.setStyleSheet("color:rgba(0,0,0,210);")
        self.label_4_esqueceuSenha.setObjectName("label_4_esqueceuSenha")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.widget_login)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(330, 350, 141, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.pushButton_5.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.label_bandeiras_2 = QtWidgets.QLabel(parent=self.page_login)
        self.label_bandeiras_2.setGeometry(QtCore.QRect(0, -10, 571, 601))
        self.label_bandeiras_2.setText("")
        self.label_bandeiras_2.setPixmap(QtGui.QPixmap("imagens/roupas.png"))
        self.label_bandeiras_2.setScaledContents(True)
        self.label_bandeiras_2.setObjectName("label_bandeiras_2")
        self.label_bandeiras_2.raise_()
        self.widget_login.raise_()
        self.StackedWidget_Paginas.addWidget(self.page_login)
        self.page_pesquisa = QtWidgets.QWidget()
        self.page_pesquisa.setObjectName("page_pesquisa")
        self.layoutWidget = QtWidgets.QWidget(parent=self.page_pesquisa)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 521, 42))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_nome = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_nome.setStyleSheet("font: italic 25pt \"Brush Script MT\"")
        self.label_nome.setObjectName("label_nome")
        self.horizontalLayout.addWidget(self.label_nome)
        self.line_nome = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.line_nome.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.line_nome.setText("")
        self.line_nome.setObjectName("line_nome")
        self.horizontalLayout.addWidget(self.line_nome)
        self.botao_pesquisar = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.botao_pesquisar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.botao_pesquisar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;")
        self.botao_pesquisar.setText("")
        self.botao_pesquisar.setIcon(icon5)
        self.botao_pesquisar.setIconSize(QtCore.QSize(25, 25))
        self.botao_pesquisar.setObjectName("botao_pesquisar")
        self.horizontalLayout.addWidget(self.botao_pesquisar)
        self.tabela = QtWidgets.QTableWidget(parent=self.page_pesquisa)
        self.tabela.setGeometry(QtCore.QRect(0, 80, 541, 289))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tabela.setFont(font)
        self.tabela.setStyleSheet("\n"
"")
        self.tabela.setObjectName("tabela")
        self.tabela.setColumnCount(6)
        self.tabela.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabela.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabela.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabela.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabela.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tabela.setHorizontalHeaderItem(5, item)
        self.label_bandeiras = QtWidgets.QLabel(parent=self.page_pesquisa)
        self.label_bandeiras.setGeometry(QtCore.QRect(-10, -10, 581, 601))
        self.label_bandeiras.setText("")
        self.label_bandeiras.setPixmap(QtGui.QPixmap("imagens/roupas.png"))
        self.label_bandeiras.setScaledContents(True)
        self.label_bandeiras.setObjectName("label_bandeiras")
        self.label_bandeiras.raise_()
        self.layoutWidget.raise_()
        self.tabela.raise_()
        self.StackedWidget_Paginas.addWidget(self.page_pesquisa)
        self.page_registrar_roupas = QtWidgets.QWidget()
        self.page_registrar_roupas.setObjectName("page_registrar_roupas")
        self.label_fundo_vestuario = QtWidgets.QLabel(parent=self.page_registrar_roupas)
        self.label_fundo_vestuario.setGeometry(QtCore.QRect(0, 0, 571, 581))
        self.label_fundo_vestuario.setText("")
        self.label_fundo_vestuario.setPixmap(QtGui.QPixmap("imagens/roupas.png"))
        self.label_fundo_vestuario.setScaledContents(True)
        self.label_fundo_vestuario.setObjectName("label_fundo_vestuario")
        self.label_nome_sistema_de_loja_2 = QtWidgets.QLabel(parent=self.page_registrar_roupas)
        self.label_nome_sistema_de_loja_2.setGeometry(QtCore.QRect(180, 0, 191, 41))
        self.label_nome_sistema_de_loja_2.setStyleSheet("font: italic 25pt \"Brush Script MT\";")
        self.label_nome_sistema_de_loja_2.setObjectName("label_nome_sistema_de_loja_2")
        self.textEdit_detalhes = QtWidgets.QTextEdit(parent=self.page_registrar_roupas)
        self.textEdit_detalhes.setGeometry(QtCore.QRect(60, 290, 401, 101))
        self.textEdit_detalhes.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"border-top:2px solid rgba(46,82,101,200);\n"
"border-left:2px solid rgba(46,82,101,200);\n"
"border-right:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.textEdit_detalhes.setObjectName("textEdit_detalhes")
        self.label_detalhes = QtWidgets.QLabel(parent=self.page_registrar_roupas)
        self.label_detalhes.setGeometry(QtCore.QRect(60, 260, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_detalhes.setFont(font)
        self.label_detalhes.setObjectName("label_detalhes")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.page_registrar_roupas)
        self.layoutWidget_2.setGeometry(QtCore.QRect(220, 110, 251, 24))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_masculino = QtWidgets.QRadioButton(parent=self.layoutWidget_2)
        self.radioButton_masculino.setChecked(True)
        self.radioButton_masculino.setObjectName("radioButton_masculino")
        self.horizontalLayout_3.addWidget(self.radioButton_masculino)
        self.radioButton_unisex = QtWidgets.QRadioButton(parent=self.layoutWidget_2)
        self.radioButton_unisex.setObjectName("radioButton_unisex")
        self.horizontalLayout_3.addWidget(self.radioButton_unisex)
        self.radioButton_feminino = QtWidgets.QRadioButton(parent=self.layoutWidget_2)
        self.radioButton_feminino.setObjectName("radioButton_feminino")
        self.horizontalLayout_3.addWidget(self.radioButton_feminino)
        self.label_tipoVestimenta = QtWidgets.QLabel(parent=self.page_registrar_roupas)
        self.label_tipoVestimenta.setGeometry(QtCore.QRect(60, 110, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_tipoVestimenta.setFont(font)
        self.label_tipoVestimenta.setObjectName("label_tipoVestimenta")
        self.line_descricao_roupa = QtWidgets.QLineEdit(parent=self.page_registrar_roupas)
        self.line_descricao_roupa.setGeometry(QtCore.QRect(60, 70, 401, 25))
        self.line_descricao_roupa.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.line_descricao_roupa.setObjectName("line_descricao_roupa")
        self.label_barra2 = QtWidgets.QLabel(parent=self.page_registrar_roupas)
        self.label_barra2.setGeometry(QtCore.QRect(60, 130, 401, 20))
        self.label_barra2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.label_barra2.setText("")
        self.label_barra2.setObjectName("label_barra2")
        self.label_barra2_2 = QtWidgets.QLabel(parent=self.page_registrar_roupas)
        self.label_barra2_2.setGeometry(QtCore.QRect(60, 180, 401, 20))
        self.label_barra2_2.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.label_barra2_2.setText("")
        self.label_barra2_2.setObjectName("label_barra2_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.page_registrar_roupas)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 170, 401, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_quantidade = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_quantidade.setFont(font)
        self.label_quantidade.setObjectName("label_quantidade")
        self.horizontalLayout_4.addWidget(self.label_quantidade)
        self.spinBox_quantidade = QtWidgets.QSpinBox(parent=self.horizontalLayoutWidget_2)
        self.spinBox_quantidade.setMaximum(99999)
        self.spinBox_quantidade.setObjectName("spinBox_quantidade")
        self.horizontalLayout_4.addWidget(self.spinBox_quantidade)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(parent=self.page_registrar_roupas)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(60, 210, 401, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_preco = QtWidgets.QLabel(parent=self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_preco.setFont(font)
        self.label_preco.setObjectName("label_preco")
        self.horizontalLayout_5.addWidget(self.label_preco)
        self.doubleSpinBox_preco = QtWidgets.QDoubleSpinBox(parent=self.horizontalLayoutWidget_3)
        self.doubleSpinBox_preco.setMaximum(9999999.0)
        self.doubleSpinBox_preco.setObjectName("doubleSpinBox_preco")
        self.horizontalLayout_5.addWidget(self.doubleSpinBox_preco)
        self.label_barra2_3 = QtWidgets.QLabel(parent=self.page_registrar_roupas)
        self.label_barra2_3.setGeometry(QtCore.QRect(60, 230, 401, 10))
        self.label_barra2_3.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;")
        self.label_barra2_3.setText("")
        self.label_barra2_3.setObjectName("label_barra2_3")
        self.line = QtWidgets.QFrame(parent=self.page_registrar_roupas)
        self.line.setGeometry(QtCore.QRect(40, 40, 441, 421))
        self.line.setStyleSheet("background-color:rgba(0,0,0,0);\n"
"border:none;\n"
"border-bottom:2px solid rgba(46,82,101,200);\n"
"border-top:2px solid rgba(46,82,101,200);\n"
"border-left:2px solid rgba(46,82,101,200);\n"
"border-right:2px solid rgba(46,82,101,200);\n"
"color:rgba(0,0,0,249);\n"
"padding-bottom: 7px;\n"
"")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.botao_entrar_vestuario = QtWidgets.QPushButton(parent=self.page_registrar_roupas)
        self.botao_entrar_vestuario.setGeometry(QtCore.QRect(60, 410, 401, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.botao_entrar_vestuario.setFont(font)
        self.botao_entrar_vestuario.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.botao_entrar_vestuario.setStyleSheet("QPushButton#PushButton{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(11, 131, 120, 219), stop:1 rgba(85, 98, 112, 226));\n"
"    color:rgba(255, 255, 255, 210);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QPushButton#pushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(150, 123, 111, 219), stop:1 rgba(85, 81, 84, 226));\n"
"}\n"
"\n"
"QPushButton#pushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:rgba(150, 123, 111, 255);\n"
"}")
        self.botao_entrar_vestuario.setObjectName("botao_entrar_vestuario")
        self.label_fundo_vestuario.raise_()
        self.line.raise_()
        self.label_nome_sistema_de_loja_2.raise_()
        self.textEdit_detalhes.raise_()
        self.label_detalhes.raise_()
        self.layoutWidget_2.raise_()
        self.label_tipoVestimenta.raise_()
        self.line_descricao_roupa.raise_()
        self.label_barra2.raise_()
        self.label_barra2_2.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.horizontalLayoutWidget_3.raise_()
        self.botao_entrar_vestuario.raise_()
        self.label_barra2_3.raise_()
        self.StackedWidget_Paginas.addWidget(self.page_registrar_roupas)
        self.page_sobre = QtWidgets.QWidget()
        self.page_sobre.setObjectName("page_sobre")
        self.label_wave = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_wave.setGeometry(QtCore.QRect(0, 0, 571, 181))
        self.label_wave.setStyleSheet("")
        self.label_wave.setText("")
        self.label_wave.setPixmap(QtGui.QPixmap("imagens/wave.svg"))
        self.label_wave.setScaledContents(True)
        self.label_wave.setObjectName("label_wave")
        self.label_img_pedro_2 = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_img_pedro_2.setGeometry(QtCore.QRect(340, 80, 140, 141))
        self.label_img_pedro_2.setStyleSheet("")
        self.label_img_pedro_2.setText("")
        self.label_img_pedro_2.setPixmap(QtGui.QPixmap("imagens/davi.jpeg"))
        self.label_img_pedro_2.setScaledContents(True)
        self.label_img_pedro_2.setObjectName("label_img_pedro_2")
        self.label_img_pedro = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_img_pedro.setGeometry(QtCore.QRect(70, 80, 140, 141))
        self.label_img_pedro.setStyleSheet("")
        self.label_img_pedro.setText("")
        self.label_img_pedro.setPixmap(QtGui.QPixmap("imagens/pedro.jpg"))
        self.label_img_pedro.setScaledContents(True)
        self.label_img_pedro.setObjectName("label_img_pedro")
        self.label_img_pedro_4 = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_img_pedro_4.setGeometry(QtCore.QRect(350, 350, 140, 140))
        self.label_img_pedro_4.setStyleSheet("")
        self.label_img_pedro_4.setText("")
        self.label_img_pedro_4.setPixmap(QtGui.QPixmap("imagens/bruno.jpg"))
        self.label_img_pedro_4.setScaledContents(True)
        self.label_img_pedro_4.setObjectName("label_img_pedro_4")
        self.label_img_pedro_3 = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_img_pedro_3.setGeometry(QtCore.QRect(60, 350, 140, 140))
        self.label_img_pedro_3.setStyleSheet("")
        self.label_img_pedro_3.setText("")
        self.label_img_pedro_3.setPixmap(QtGui.QPixmap("imagens/maeldson.jpeg"))
        self.label_img_pedro_3.setScaledContents(True)
        self.label_img_pedro_3.setObjectName("label_img_pedro_3")
        self.label_fundo_sobre = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_fundo_sobre.setGeometry(QtCore.QRect(-10, 0, 581, 581))
        self.label_fundo_sobre.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.label_fundo_sobre.setText("")
        self.label_fundo_sobre.setObjectName("label_fundo_sobre")
        self.label_title = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_title.setGeometry(QtCore.QRect(100, 10, 441, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(39, 48, 54);\n"
"border:none")
        self.label_title.setObjectName("label_title")
        self.label_nome_3 = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_nome_3.setGeometry(QtCore.QRect(360, 50, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nome_3.setFont(font)
        self.label_nome_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_nome_3.setObjectName("label_nome_3")
        self.label_nome_5 = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_nome_5.setGeometry(QtCore.QRect(50, 320, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nome_5.setFont(font)
        self.label_nome_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_nome_5.setObjectName("label_nome_5")
        self.label_nome_2 = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_nome_2.setGeometry(QtCore.QRect(90, 50, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nome_2.setFont(font)
        self.label_nome_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_nome_2.setObjectName("label_nome_2")
        self.label_nome_4 = QtWidgets.QLabel(parent=self.page_sobre)
        self.label_nome_4.setGeometry(QtCore.QRect(370, 320, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nome_4.setFont(font)
        self.label_nome_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_nome_4.setObjectName("label_nome_4")
        self.textBrowser_pedro = QtWidgets.QTextBrowser(parent=self.page_sobre)
        self.textBrowser_pedro.setGeometry(QtCore.QRect(40, 220, 201, 111))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_pedro.setFont(font)
        self.textBrowser_pedro.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.textBrowser_pedro.setOpenExternalLinks(True)
        self.textBrowser_pedro.setObjectName("textBrowser_pedro")
        self.textBrowser_davi = QtWidgets.QTextBrowser(parent=self.page_sobre)
        self.textBrowser_davi.setGeometry(QtCore.QRect(300, 230, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_davi.setFont(font)
        self.textBrowser_davi.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.textBrowser_davi.setOpenExternalLinks(True)
        self.textBrowser_davi.setObjectName("textBrowser_davi")
        self.textBrowser_maldades = QtWidgets.QTextBrowser(parent=self.page_sobre)
        self.textBrowser_maldades.setGeometry(QtCore.QRect(10, 490, 251, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_maldades.setFont(font)
        self.textBrowser_maldades.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.textBrowser_maldades.setOpenExternalLinks(True)
        self.textBrowser_maldades.setObjectName("textBrowser_maldades")
        self.textBrowser_bruno = QtWidgets.QTextBrowser(parent=self.page_sobre)
        self.textBrowser_bruno.setGeometry(QtCore.QRect(310, 480, 221, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_bruno.setFont(font)
        self.textBrowser_bruno.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.textBrowser_bruno.setOpenExternalLinks(True)
        self.textBrowser_bruno.setObjectName("textBrowser_bruno")
        self.label_fundo_sobre.raise_()
        self.label_wave.raise_()
        self.label_img_pedro_2.raise_()
        self.label_img_pedro.raise_()
        self.label_img_pedro_4.raise_()
        self.label_img_pedro_3.raise_()
        self.label_title.raise_()
        self.label_nome_3.raise_()
        self.label_nome_5.raise_()
        self.label_nome_2.raise_()
        self.label_nome_4.raise_()
        self.textBrowser_pedro.raise_()
        self.textBrowser_davi.raise_()
        self.textBrowser_maldades.raise_()
        self.textBrowser_bruno.raise_()
        self.StackedWidget_Paginas.addWidget(self.page_sobre)
        self.label_nome_usuario = QtWidgets.QLabel(parent=self.Menu)
        self.label_nome_usuario.setGeometry(QtCore.QRect(100, 220, 91, 31))
        self.label_nome_usuario.setAutoFillBackground(False)
        self.label_nome_usuario.setStyleSheet("color:\'white\';font: italic 20pt \"Brush Script MT\";")
        self.label_nome_usuario.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_nome_usuario.setScaledContents(False)
        self.label_nome_usuario.setWordWrap(True)
        self.label_nome_usuario.setObjectName("label_nome_usuario")
        self.label_left_Image.raise_()
        self.verticalWidget_miniMenu.raise_()
        self.label_nome_sistema_de_loja.raise_()
        self.StackedWidget_Paginas.raise_()
        self.label_nome_usuario.raise_()
        LojadeRoupa.setCentralWidget(self.Menu)

        self.retranslateUi(LojadeRoupa)
        self.StackedWidget_Paginas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LojadeRoupa)

    def retranslateUi(self, LojadeRoupa):
        _translate = QtCore.QCoreApplication.translate
        LojadeRoupa.setWindowTitle(_translate("LojadeRoupa", "Loja de Roupa"))
        self.pushButton_login.setText(_translate("LojadeRoupa", "Login"))
        self.pushButton_cadastrar.setText(_translate("LojadeRoupa", "Cadastrar"))
        self.pushButton_cadastrar_usuario.setText(_translate("LojadeRoupa", "Usuario"))
        self.pushButton_cadastrar_vestuario.setText(_translate("LojadeRoupa", "vestuário"))
        self.pushButton_pesquisa.setText(_translate("LojadeRoupa", "Pesquisa"))
        self.pushButton_sobre.setText(_translate("LojadeRoupa", "Sobre"))
        self.label_nome_sistema_de_loja.setText(_translate("LojadeRoupa", "Sistema da Loja"))
        self.label_login.setText(_translate("LojadeRoupa", "Login"))
        self.line_usuario.setPlaceholderText(_translate("LojadeRoupa", "Nome do Usuário"))
        self.line_senha.setPlaceholderText(_translate("LojadeRoupa", "Senha"))
        self.botao_entrar.setText(_translate("LojadeRoupa", "ENTRAR"))
        self.label_4_esqueceuSenha.setText(_translate("LojadeRoupa", "Não tem uma conta? cadastre-se"))
        self.pushButton_4.setText(_translate("LojadeRoupa", "Q"))
        self.pushButton_3.setText(_translate("LojadeRoupa", "D"))
        self.pushButton_2.setText(_translate("LojadeRoupa", "E"))
        self.pushButton_5.setText(_translate("LojadeRoupa", "M"))
        self.label_nome.setText(_translate("LojadeRoupa", "Nome:"))
        self.line_nome.setPlaceholderText(_translate("LojadeRoupa", "busca..."))
        item = self.tabela.horizontalHeaderItem(0)
        item.setText(_translate("LojadeRoupa", "Código"))
        item = self.tabela.horizontalHeaderItem(1)
        item.setText(_translate("LojadeRoupa", "Nome"))
        item = self.tabela.horizontalHeaderItem(2)
        item.setText(_translate("LojadeRoupa", "Vestimenta"))
        item = self.tabela.horizontalHeaderItem(3)
        item.setText(_translate("LojadeRoupa", "Quantidade"))
        item = self.tabela.horizontalHeaderItem(4)
        item.setText(_translate("LojadeRoupa", "Preço"))
        item = self.tabela.horizontalHeaderItem(5)
        item.setText(_translate("LojadeRoupa", "Detalhes"))
        self.label_nome_sistema_de_loja_2.setText(_translate("LojadeRoupa", "Registrar Roupas"))
        self.label_detalhes.setText(_translate("LojadeRoupa", "Detalhes:"))
        self.radioButton_masculino.setText(_translate("LojadeRoupa", "Masculina"))
        self.radioButton_unisex.setText(_translate("LojadeRoupa", "Feminina"))
        self.radioButton_feminino.setText(_translate("LojadeRoupa", "Unisex"))
        self.label_tipoVestimenta.setText(_translate("LojadeRoupa", "Tipo de Vestimenta:"))
        self.line_descricao_roupa.setPlaceholderText(_translate("LojadeRoupa", "Descrição da Roupa"))
        self.label_quantidade.setText(_translate("LojadeRoupa", "Quantidade"))
        self.label_preco.setText(_translate("LojadeRoupa", "Preço:"))
        self.botao_entrar_vestuario.setText(_translate("LojadeRoupa", "REGISTRAR"))
        self.label_title.setText(_translate("LojadeRoupa", "Sobre os desenvolvedores"))
        self.label_nome_3.setText(_translate("LojadeRoupa", "Davi Gledson"))
        self.label_nome_5.setText(_translate("LojadeRoupa", "Maeldson Cavalcante"))
        self.label_nome_2.setText(_translate("LojadeRoupa", "Pedro Ricardo"))
        self.label_nome_4.setText(_translate("LojadeRoupa", "Alisson Bruno"))
        self.textBrowser_pedro.setHtml(_translate("LojadeRoupa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Semibold\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\">Estudante de informática no IFRN. Atuamente desenvolvedor de software no IFRN no Campus Mossoró. Sou de Upanema e gosto de música e de escrever. Você pode me seguir no Github: </span><a href=\"https://github.com/pedroricardo14\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">https://github.com/pedroricardo14</span></a><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"> </span></p></body></html>"))
        self.textBrowser_davi.setHtml(_translate("LojadeRoupa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Semibold\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\">Desenvolvedor. Você pode me seguir no Github: </span><a href=\"https://github.com/davigledson\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">https://github.com/davigledson</span></a><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"> </span></p></body></html>"))
        self.textBrowser_maldades.setHtml(_translate("LojadeRoupa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Semibold\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\">Sou Maeldson, moro em Upanema-RN, gosto de ler e um grande fã de One Piece. Você pode me seguir no Github:</span><a href=\"https://github.com/pedroricardo14\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">https://github.com/pedroricardo14</span></a><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"> </span></p></body></html>"))
        self.textBrowser_bruno.setHtml(_translate("LojadeRoupa", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Semibold\'; font-size:8.25pt; font-weight:600; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7.8pt;\">Sou Alisson Bruno,tenho 20 anos e curso informática no IFRN e Administração na Uern, adquirido experiência incrível durante essa jornada. Você pode me seguir no Github: </span><a href=\"https://github.com/Bruno768\"><span style=\" font-size:8pt; text-decoration: underline; color:#0000ff;\">https://github.com/Bruno768</span></a></p></body></html>"))
        self.label_nome_usuario.setText(_translate("LojadeRoupa", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))

        self.pushButton_sobre.clicked.connect(self.trocarPaginaSobre)
        self.pushButton_pesquisa.clicked.connect(self.trocarPaginaPesquisa)
        self.pushButton_cadastrar_vestuario.clicked.connect(self.trocarPaginaVestuario)
        self.pushButton_login.clicked.connect(self.trocarPaginaLogin)
        self.pushButton_cadastrar_usuario.clicked.connect(self.abrirPaginaCadastrar)

        self.botao_pesquisar.clicked.connect(self.pesquisar)
        self.botao_entrar.clicked.connect(self.login)
        self.botao_entrar_vestuario.clicked.connect(self.cadastrarRoupas)

    def trocarPaginaPesquisa(self):
        if self.login() == True:
            self.StackedWidget_Paginas.setCurrentWidget(self.page_pesquisa)
        # else:
        # msg = QMessageBox()
        # msg.setWindowTitle('Aviso')
        # msg.setText('Faça login para acessar o sistema')
        # msg.exec()
        # return False
        print('pesquisa')

    def trocarPaginaLogin(self):
        if self.login() == True:
            self.StackedWidget_Paginas.setCurrentWidget(self.page_login)

        print('login')

    def trocarPaginaSobre(self):
        if self.login() == True:
            self.StackedWidget_Paginas.setCurrentWidget(self.page_sobre)

        print('sobre')

    def trocarPaginaVestuario(self):
        if self.login() == True:
            self.StackedWidget_Paginas.setCurrentWidget(self.page_registrar_roupas)

        print('sobre')

    def abrirPaginaCadastrar(self):
        if self.login() == True:
            from cadastro import Ui_telaCadastro
            # cria uma tela vazia
            self.tela = QtWidgets.QMainWindow()

            # criar um objeto da tela que deseja exibir
            self.cadastro = Ui_telaCadastro()

            # associar a tela vazia com o código da tela a exibir
            self.cadastro.setupUi(self.tela)

            # exibir a nova tela

            self.tela.show()

    def pesquisar(self):
        nome = self.line_nome.text()
        sql = '''SELECT * FROM roupas WHERE NOME LIKE %s'''
        cursor.execute(sql, ("%" + nome + "%",))
        dados = cursor.fetchall()
        print(dados)

        self.tabela.setRowCount(len(dados))
        cont = 0  # contador de linhas
        for linha in dados:
            codigo = QTableWidgetItem(str(linha[0]))
            nome = QTableWidgetItem(linha[1])
            tipoVestimenta = QTableWidgetItem(linha[2])
            quantidade = QTableWidgetItem(str(linha[3]))
            preco = QTableWidgetItem(str(linha[4]))
            detalhes = QTableWidgetItem(linha[5])

            self.tabela.setItem(cont, 0, codigo)
            self.tabela.setItem(cont, 1, nome)
            self.tabela.setItem(cont, 2, tipoVestimenta)
            self.tabela.setItem(cont, 3, quantidade)
            self.tabela.setItem(cont, 4, preco)
            self.tabela.setItem(cont, 5, detalhes)
            cont += 1
        self.tabela.show()

    def login(self):
        nome = self.line_usuario.text()
        senha = self.line_senha.text()
        sql = '''SELECT * FROM usuarios WHERE nome = %s AND senha = %s'''
        cursor.execute(sql, (nome, senha))
        dados = cursor.fetchall()
        # print(dados)

        if len(dados) == 0:  # não encontrou
            msg = QMessageBox()
            msg.setWindowTitle('Aviso')
            msg.setText('Acesso negado.')
            msg.exec()
            return False
        else:
            self.StackedWidget_Paginas.setCurrentWidget(self.page_pesquisa)
            self.label_nome_usuario.setText(nome)

            self.pushButton_login.setDisabled(True)
            return True

    def cadastrarRoupas(self):
        descricao = self.line_descricao_roupa.text()

        tipoVestimenta = ""
        if self.radioButton_masculino.isChecked():
            tipoVestimenta = "Masculino"

            #estao trocados
        elif self.radioButton_feminino.isChecked():
            tipoVestimenta = "Unisex"
        elif self.radioButton_unisex.isChecked():
            tipoVestimenta = "Feminino"

        quantidade = self.spinBox_quantidade.text()
        preco = self.doubleSpinBox_preco.text()
        detalhes = self.textEdit_detalhes.toPlainText()

        print(descricao, tipoVestimenta, quantidade, preco, detalhes)

        sql = "INSERT INTO roupas VALUES(null,%s,%s,%s,%s,%s)"
        cursor.execute(sql, (descricao, tipoVestimenta, quantidade, preco, detalhes))
        conexao.commit()

        msg = QMessageBox()
        msg.setWindowTitle('AVISO')
        msg.setText('Inserido com sucesso')
        msg.exec()

        self.line_descricao_roupa.setText('')
        self.radioButton_feminino.setChecked(True)
        self.radioButton_unisex.setChecked(False)  # opcional
        self.radioButton_masculino.setChecked(False)
        self.spinBox_quantidade.setValue(0)
        self.doubleSpinBox_preco.setValue(0)
        self.textEdit_detalhes.setText('')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LojadeRoupa = QtWidgets.QMainWindow()
    ui = Ui_LojadeRoupa()
    ui.setupUi(LojadeRoupa)
    LojadeRoupa.show()
    sys.exit(app.exec())
