# Form implementation generated from reading ui file 'pesquisa.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PesqAluno(object):
    def setupUi(self, PesqAluno):
        PesqAluno.setObjectName("PesqAluno")
        PesqAluno.resize(521, 338)
        self.centralwidget_pesquisa = QtWidgets.QWidget(parent=PesqAluno)
        self.centralwidget_pesquisa.setObjectName("centralwidget_pesquisa")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget_pesquisa)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_nome = QtWidgets.QLabel(parent=self.centralwidget_pesquisa)
        self.label_nome.setStyleSheet("font: 8pt \"Cooper Black\";")
        self.label_nome.setObjectName("label_nome")
        self.horizontalLayout.addWidget(self.label_nome)
        self.line_nome = QtWidgets.QLineEdit(parent=self.centralwidget_pesquisa)
        self.line_nome.setStyleSheet("color:rgb(170, 255, 255)")
        self.line_nome.setObjectName("line_nome")
        self.horizontalLayout.addWidget(self.line_nome)
        self.botao_pesquisar = QtWidgets.QPushButton(parent=self.centralwidget_pesquisa)
        self.botao_pesquisar.setStyleSheet("font: 8pt \"Cooper Black\";")
        self.botao_pesquisar.setObjectName("botao_pesquisar")
        self.horizontalLayout.addWidget(self.botao_pesquisar)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tabela = QtWidgets.QTableWidget(parent=self.centralwidget_pesquisa)
        self.tabela.setStyleSheet("font: 8pt \"Copperplate Gothic Bold\";\n"
"background-color: blue;\n"
";")
        self.tabela.setObjectName("tabela")
        self.tabela.setColumnCount(4)
        self.tabela.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        item.setFont(font)
        self.tabela.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        item.setFont(font)
        self.tabela.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        item.setFont(font)
        self.tabela.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        item.setFont(font)
        self.tabela.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tabela)
        PesqAluno.setCentralWidget(self.centralwidget_pesquisa)

        self.retranslateUi(PesqAluno)
        QtCore.QMetaObject.connectSlotsByName(PesqAluno)

    def retranslateUi(self, PesqAluno):
        _translate = QtCore.QCoreApplication.translate
        PesqAluno.setWindowTitle(_translate("PesqAluno", "Pesquisa de Aluno"))
        self.label_nome.setText(_translate("PesqAluno", "Nome:"))
        self.botao_pesquisar.setText(_translate("PesqAluno", "Pesquisar"))
        item = self.tabela.horizontalHeaderItem(0)
        item.setText(_translate("PesqAluno", "Código"))
        item = self.tabela.horizontalHeaderItem(1)
        item.setText(_translate("PesqAluno", "Nome"))
        item = self.tabela.horizontalHeaderItem(2)
        item.setText(_translate("PesqAluno", "Preço"))
        item = self.tabela.horizontalHeaderItem(3)
        item.setText(_translate("PesqAluno", "Marca"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PesqAluno = QtWidgets.QMainWindow()
    ui = Ui_PesqAluno()
    ui.setupUi(PesqAluno)
    PesqAluno.show()
    sys.exit(app.exec())
