# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import mysql.connector



conexao=mysql.connector.connect(
    host='localhost',
    user='root',
    password="",
    database="farmacia"
)
cursor=conexao.cursor()
print("conectado")
class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(520, 445)
        login.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=login)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.label_usuario = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_usuario.setFont(font)
        self.label_usuario.setStyleSheet("\n"
"color: rgb(81, 124, 178);")
        self.label_usuario.setObjectName("label_usuario")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_usuario)
        self.label_senha = QtWidgets.QLabel(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_senha.setFont(font)
        self.label_senha.setStyleSheet("color: rgb(81, 124, 178);")
        self.label_senha.setObjectName("label_senha")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_senha)
        self.line_senha = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.line_senha.setFont(font)
        self.line_senha.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.line_senha.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.line_senha.setObjectName("line_senha")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_senha)
        self.botao_entrar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botao_entrar.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.botao_entrar.setFont(font)
        self.botao_entrar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(81, 124, 178);")
        self.botao_entrar.setObjectName("botao_entrar")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.botao_entrar)
        self.line_usuario = QtWidgets.QLineEdit(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(9)
        self.line_usuario.setFont(font)
        self.line_usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.line_usuario.setObjectName("line_usuario")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.line_usuario)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imagens/logo.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.label_2)
        login.setCentralWidget(self.centralwidget)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

        self.botao_entrar.clicked.connect(self.login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Login"))
        self.label_usuario.setText(_translate("login", "Usuário:"))
        self.label_senha.setText(_translate("login", "Senha:"))
        self.botao_entrar.setText(_translate("login", "ENTRAR"))

    def login(self):
        nome = self.line_usuario.text()
        senha = self.line_senha.text()

        sql = '''SELECT * FROM usuarios WHERE nome = %s
                AND senha = %s'''
        cursor.execute(sql, (nome, senha))
        dados = cursor.fetchall()

        if len(dados) == 0:  # Não encontrou
            msg = QMessageBox()
            msg.setWindowTitle("Aviso")
            msg.setText("Acesso negado.")
            msg.exec()

        else:
            # importar a classe da tela que deseja abrir
            from menu import Ui_Menu
            # criar uma tela vazia
            self.tela = QtWidgets.QMainWindow()
            # criar um objeto da tela que deseja exibir
            self.menu = Ui_Menu()
            # associar a tela vazia com o código da tela a exibir
            self.menu.setupUi(self.tela)
            # exibir a nova tela
            self.tela.show()
            # fechar a tela de login
            login.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec())
