# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.5.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(917, 714)
        self.centralwidget = QtWidgets.QWidget(parent=Menu)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_cadastro = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botao_cadastro.setGeometry(QtCore.QRect(-10, 0, 481, 381))
        self.botao_cadastro.setText("")
        self.botao_cadastro.setIconSize(QtCore.QSize(160, 150))
        self.botao_cadastro.setObjectName("botao_cadastro")
        self.botao_pesquisa = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botao_pesquisa.setGeometry(QtCore.QRect(470, -10, 451, 381))
        self.botao_pesquisa.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/lupa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.botao_pesquisa.setIcon(icon)
        self.botao_pesquisa.setIconSize(QtCore.QSize(160, 150))
        self.botao_pesquisa.setObjectName("botao_pesquisa")
        self.botao_sobre = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botao_sobre.setGeometry(QtCore.QRect(-10, 370, 481, 481))
        self.botao_sobre.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Downloads/botao-de-informacao.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.botao_sobre.setIcon(icon1)
        self.botao_sobre.setIconSize(QtCore.QSize(160, 150))
        self.botao_sobre.setObjectName("botao_sobre")
        self.label_sobre_imagem = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_sobre_imagem.setGeometry(QtCore.QRect(150, 450, 180, 161))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sobre_imagem.setFont(font)
        self.label_sobre_imagem.setStyleSheet("color: rgb(108, 168, 218);")
        self.label_sobre_imagem.setText("")
        self.label_sobre_imagem.setPixmap(QtGui.QPixmap("icones/botao-de-informacao.png"))
        self.label_sobre_imagem.setScaledContents(True)
        self.label_sobre_imagem.setObjectName("label_sobre_imagem")
        self.label_fechar_imagem = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_fechar_imagem.setGeometry(QtCore.QRect(580, 450, 180, 161))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fechar_imagem.setFont(font)
        self.label_fechar_imagem.setStyleSheet("color: rgb(108, 168, 218);")
        self.label_fechar_imagem.setText("")
        self.label_fechar_imagem.setPixmap(QtGui.QPixmap("icones/fechar.png"))
        self.label_fechar_imagem.setScaledContents(True)
        self.label_fechar_imagem.setObjectName("label_fechar_imagem")
        self.label_sobre = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_sobre.setGeometry(QtCore.QRect(220, 630, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_sobre.setFont(font)
        self.label_sobre.setStyleSheet("color: rgb(108, 168, 218);")
        self.label_sobre.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_sobre.setObjectName("label_sobre")
        self.botao_fechar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.botao_fechar.setGeometry(QtCore.QRect(470, 370, 451, 481))
        self.botao_fechar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Downloads/fechar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.botao_fechar.setIcon(icon2)
        self.botao_fechar.setIconSize(QtCore.QSize(160, 150))
        self.botao_fechar.setObjectName("botao_fechar")
        self.label_pesquisar_imagem_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pesquisar_imagem_2.setGeometry(QtCore.QRect(600, 90, 171, 151))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_pesquisar_imagem_2.setFont(font)
        self.label_pesquisar_imagem_2.setStyleSheet("color: rgb(108, 168, 218);")
        self.label_pesquisar_imagem_2.setText("")
        self.label_pesquisar_imagem_2.setPixmap(QtGui.QPixmap("icones/lupa.png"))
        self.label_pesquisar_imagem_2.setScaledContents(True)
        self.label_pesquisar_imagem_2.setObjectName("label_pesquisar_imagem_2")
        self.label_cadastrar_imagem_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cadastrar_imagem_3.setGeometry(QtCore.QRect(150, 90, 180, 161))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_cadastrar_imagem_3.setFont(font)
        self.label_cadastrar_imagem_3.setStyleSheet("color: rgb(108, 168, 218);")
        self.label_cadastrar_imagem_3.setText("")
        self.label_cadastrar_imagem_3.setPixmap(QtGui.QPixmap("icones/cadastro (1).png"))
        self.label_cadastrar_imagem_3.setScaledContents(True)
        self.label_cadastrar_imagem_3.setObjectName("label_cadastrar_imagem_3")
        self.label_cadastro = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_cadastro.setGeometry(QtCore.QRect(200, 270, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_cadastro.setFont(font)
        self.label_cadastro.setStyleSheet("color: rgb(108, 168, 218);")
        self.label_cadastro.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_cadastro.setObjectName("label_cadastro")
        self.label_pesquisa = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pesquisa.setGeometry(QtCore.QRect(640, 260, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_pesquisa.setFont(font)
        self.label_pesquisa.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_pesquisa.setStyleSheet("color: rgb(108, 168, 218);")
        self.label_pesquisa.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_pesquisa.setObjectName("label_pesquisa")
        self.label_fechar = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_fechar.setGeometry(QtCore.QRect(650, 630, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Sans Serif Collection")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_fechar.setFont(font)
        self.label_fechar.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_fechar.setStyleSheet("color: rgb(108, 168, 218);")
        self.label_fechar.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_fechar.setObjectName("label_fechar")
        self.botao_fechar.raise_()
        self.botao_cadastro.raise_()
        self.botao_pesquisa.raise_()
        self.botao_sobre.raise_()
        self.label_sobre_imagem.raise_()
        self.label_fechar_imagem.raise_()
        self.label_sobre.raise_()
        self.label_pesquisar_imagem_2.raise_()
        self.label_cadastrar_imagem_3.raise_()
        self.label_cadastro.raise_()
        self.label_pesquisa.raise_()
        self.label_fechar.raise_()
        Menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)


        self.botao_sobre.clicked.connect(self.sobre)
        self.botao_fechar.clicked.connect(self.fecharMenu)
        self.botao_cadastro.clicked.connect(self.cadastro)
        self.botao_pesquisa.clicked.connect(self.pesquisa)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Menu"))
        self.label_sobre.setText(_translate("Menu", "Sobre"))
        self.label_cadastro.setText(_translate("Menu", "Cadastro"))
        self.label_pesquisa.setText(_translate("Menu", "Pesquisa"))
        self.label_fechar.setText(_translate("Menu", "Fechar"))






    def sobre(self):

        from sobre2 import Ui_Sobre
        # criar uma tela vazia
        self.tela = QtWidgets.QMainWindow()
        # criar um objeto da tela que deseja exibir
        self.sobre = Ui_Sobre()
        # associar a tela vazia com o código da tela a exibir
        self.sobre.setupUi(self.tela)
        # exibir a nova tela
        self.tela.show()

        # fechar a tela de login
    def cadastro(self):
        from cadastro import Ui_cadastro
        # criar uma tela vazia
        self.tela = QtWidgets.QMainWindow()
        # criar um objeto da tela que deseja exibir
        self.cadastro = Ui_cadastro()
        # associar a tela vazia com o código da tela a exibir
        self.cadastro.setupUi(self.tela)
        # exibir a nova tela
        self.tela.show()

    def pesquisa(self):
        from pesquisa import Ui_MainWindow
        # criar uma tela vazia
        self.tela = QtWidgets.QMainWindow()
        # criar um objeto da tela que deseja exibir
        self.cadastro = Ui_MainWindow()
        # associar a tela vazia com o código da tela a exibir
        self.cadastro.setupUi(self.tela)
        # exibir a nova tela
        self.tela.show()

    def fecharMenu(self):
        Menu.close()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QMainWindow()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec())
