# Form implementation generated from reading ui file 'farm.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox, QTableWidgetItem

import mysql.connector
conexao=mysql.connector.connect(
    host='localhost',
    user='root',
    password="",
    database="farmacia"
)
cursor=conexao.cursor()
print("conectado")

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 537)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 1101, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_sobre = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_sobre.setFont(font)
        self.label_sobre.setStyleSheet("color: rgb(67, 106, 155);")
        self.label_sobre.setObjectName("label_sobre")
        self.horizontalLayout.addWidget(self.label_sobre)
        self.line_sobre = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.line_sobre.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.line_sobre.setObjectName("line_sobre")
        self.horizontalLayout.addWidget(self.line_sobre)
        self.botao_pesquisar = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("SansSerif")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.botao_pesquisar.setFont(font)
        self.botao_pesquisar.setStyleSheet("background-color: rgb(108, 168, 218);\n"
"color: rgb(255, 255, 255);")
        self.botao_pesquisar.setObjectName("botao_pesquisar")
        self.botao_pesquisar.clicked.connect(self.pesquisar)
        self.horizontalLayout.addWidget(self.botao_pesquisar)
        self.Tabela = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.Tabela.setGeometry(QtCore.QRect(0, 50, 1101, 484))
        self.Tabela.setStyleSheet("color: rgb(67, 106, 155);")
        self.Tabela.setObjectName("Tabela")
        self.Tabela.setColumnCount(11)
        self.Tabela.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Tabela.setHorizontalHeaderItem(10, item)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_sobre.setText(_translate("MainWindow", "Sobre:"))
        self.botao_pesquisar.setText(_translate("MainWindow", "Pesquisar"))
        item = self.Tabela.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Código"))
        item = self.Tabela.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.Tabela.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Fabricante"))
        item = self.Tabela.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Estoque"))
        item = self.Tabela.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Validade"))
        item = self.Tabela.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Valor de compra"))
        item = self.Tabela.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Valor de venda"))
        item = self.Tabela.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Controlada"))
        item = self.Tabela.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Medida"))
        item = self.Tabela.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Descrição"))
        item = self.Tabela.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Categoria"))


    def pesquisar(self):
        nome_do_produto=self.line_sobre.text()
        sql='''SELECT * FROM produtos WHERE nome LIKE %s'''
        cursor.execute(sql, ("%" + nome_do_produto + "%",))

        dados=cursor.fetchall()
        print(dados)

        self.Tabela.setRowCount(len(dados))


        cont=0
        for linha in dados:
            nome=QTableWidgetItem(str(linha[0]))
            codigo=QTableWidgetItem(str(linha[1]))
            fabrica=QTableWidgetItem(str(linha[2]))
            estoque=QTableWidgetItem(str(linha[3]))
            validade=QTableWidgetItem(str(linha[4]))
            valor_compra=QTableWidgetItem(str(linha[5]))
            valor_venda=QTableWidgetItem(str(linha[6]))
            categoria=QTableWidgetItem(str(linha[7]))
            controlada=QTableWidgetItem(str(linha[8]))
            medida=QTableWidgetItem(str(linha[9]))
            descricao=QTableWidgetItem(str(linha[10]))


            self.Tabela.setItem(cont, 0, nome)
            self.Tabela.setItem(cont, 1, codigo)
            self.Tabela.setItem(cont, 2, fabrica)
            self.Tabela.setItem(cont, 3, estoque)
            self.Tabela.setItem(cont, 4, validade)
            self.Tabela.setItem(cont, 5, valor_compra)
            self.Tabela.setItem(cont, 6, valor_venda)
            self.Tabela.setItem(cont, 7, categoria)
            self.Tabela.setItem(cont, 8, controlada)
            self.Tabela.setItem(cont, 9, medida)
            self.Tabela.setItem(cont, 10, descricao)
            cont+=1 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
